a = imread('Test_images\test.jpg');
b = rgb2gray(a);
c = im2bw(b);
se = strel('disk',9);
imd = imdilate(c,se);
ime = imerode(c,se);
subplot(5,2,1),imshow(b),title('gray');
subplot(5,2,2),imshow(c),title('b&w');
subplot(5,2,3),imshow(imd),title('dilated');
subplot(5,2,4),imshow(ime),title('eroded');
e = imd-c;
f = c-ime;
subplot(5,2,5),imshow(e),title('border');
subplot(5,2,6),imshow(f),title('border');
see = strel('line',15,25);
imd1 = imdilate(c,see);
ime1 = imerode(c,see);
subplot(5,2,7),imshow(ime1),title('eroded 2');
subplot(5,2,8),imshow(imd1),title('dilated 2');
se1 = strel('rectangle',[20 16]);
imd2 = imdilate(c,se1);
ime2 = imerode(c,se1);
subplot(5,2,9),imshow(imd2),title('dilated3');
subplot(5,2,10),imshow(ime2),title('eroded 2');