a = imread('Test_images\apple3.bmp');
b = imread('Test_images\images.jpg');
a = imresize(a,[256 256]);
b = imresize(b,[256 256]);
a = rgb2gray(a);
b = rgb2gray(b);
c = fft2(a);
d = fft2(b);
e = angle(c);
f = angle(d);
g = ifft2(abs(c).*exp(i*f));
h = ifft2(abs(d).*exp(i*e));
x = fftshift(abs(c));
y = fftshift(abs(d));
subplot(4,3,1),imshow(a);
subplot(4,3,2),imshow(255*mat2gray(x));
subplot(4,3,3),imshow(255*mat2gray(y));
%subplot(4,3,4),imshow(d);
%subplot(4,3,5),imshow(e);
%subplot(4,3,6),imshow(f);
subplot(4,3,7),imshow(uint8(g));
subplot(4,3,8),imshow(uint8(h));